-- AiX Club initial Supabase schema.
-- Runtime access is server-side through Postgres connection env vars.
-- Direct browser/Data API access is intentionally locked down.

create table if not exists public.courses (
  id text primary key,
  name text not null,
  price integer default 0,
  originalprice integer default 0,
  instructor text default '',
  level text default 'beginner',
  hours integer default 0,
  lessons integer default 0,
  students integer default 0,
  rating double precision default 0,
  ratingcount integer default 0,
  image text default '',
  description text default '',
  type text default '',
  status text default '',
  subtitle text default '',
  overview text default '',
  durationtext text default '',
  lessonstext text default '',
  learners text default '',
  schedule text default '',
  skills text default '[]',
  tools text default '[]',
  outcomes text default '[]',
  info text default '[]',
  syllabus text default '[]',
  project text default '',
  faq text default '[]',
  brandfocus text default '[]',
  sortorder integer default 0,
  featured integer default 0
);

create table if not exists public.leads (
  id text primary key,
  firstname text not null,
  lastname text default '',
  email text not null,
  phone text default '',
  lineid text default '',
  business text default '',
  courseid text default '',
  membership text default 'explorer',
  payment text default '',
  status text default 'new',
  createdat text default (timezone('utc', now())::text)
);

create table if not exists public.users (
  id integer generated by default as identity primary key,
  name text not null,
  email text unique not null,
  password text not null,
  tier text default 'explorer',
  enrolledcourses text default '[]',
  joineddate text default (timezone('utc', now())::text)
);

create table if not exists public.members (
  id text primary key,
  firstname text not null,
  lastname text default '',
  email text unique not null,
  phone text unique not null,
  lineid text default '',
  business text default '',
  courseid text default '',
  membership text default 'aix-member',
  payment text default 'promptpay',
  status text default 'active',
  authprovider text default 'email',
  googlesub text unique,
  picture text default '',
  emailverified integer default 0,
  phoneverified integer default 0,
  consentaccepted integer default 0,
  marketingconsent integer default 0,
  createdat text default (timezone('utc', now())::text),
  updatedat text default (timezone('utc', now())::text),
  lastloginat text default '',
  displayname text default '',
  avatarurl text default '',
  paymentstatus text default 'unpaid',
  paidat text default '',
  expiresat text default '',
  passwordhash text default '',
  role text default 'member',
  paymentmethod text default '',
  paymentprovider text default '',
  paymentamount integer default 0,
  paymentcurrency text default 'thb',
  stripecustomerid text default '',
  stripesessionid text default '',
  stripepaymentintentid text default ''
);

create table if not exists public.packages (
  id text primary key,
  name text not null,
  price integer default 0,
  period text default '',
  icon text default '',
  features text default '[]',
  popular integer default 0,
  enabled integer default 1
);

create table if not exists public.sms_verifications (
  id text primary key,
  phone text not null,
  purpose text default 'register',
  codehash text not null,
  attempts integer default 0,
  expiresat text not null,
  verifiedat text default '',
  createdat text default (timezone('utc', now())::text),
  lastsentat text default ''
);

create index if not exists idx_sms_verifications_phone
  on public.sms_verifications(phone, purpose, createdat);

create table if not exists public.course_replays (
  id text primary key,
  courseid text not null,
  title text not null,
  description text default '',
  videourl text default '',
  filepath text default '',
  durationtext text default '',
  visibility text default 'members',
  sortorder integer default 0,
  createdat text default (timezone('utc', now())::text),
  updatedat text default (timezone('utc', now())::text)
);

create index if not exists idx_course_replays_course
  on public.course_replays(courseid, sortorder, createdat);

create table if not exists public.member_resources (
  id text primary key,
  courseid text default '',
  type text default 'tool',
  title text not null,
  description text default '',
  url text default '',
  filepath text default '',
  filename text default '',
  tags text default '[]',
  visibility text default 'members',
  sortorder integer default 0,
  createdat text default (timezone('utc', now())::text),
  updatedat text default (timezone('utc', now())::text)
);

create index if not exists idx_member_resources_course
  on public.member_resources(courseid, sortorder, createdat);

create table if not exists public.class_schedules (
  id text primary key,
  courseid text not null,
  title text not null,
  description text default '',
  startsat text not null,
  endsat text default '',
  meetingurl text default '',
  notifybeforeminutes integer default 1440,
  notifystatus text default 'scheduled',
  createdat text default (timezone('utc', now())::text),
  updatedat text default (timezone('utc', now())::text)
);

create index if not exists idx_class_schedules_course
  on public.class_schedules(courseid, startsat);

create table if not exists public.notifications (
  id text primary key,
  memberid text not null,
  scheduleid text default '',
  channel text default 'dashboard',
  title text not null,
  message text default '',
  status text default 'unread',
  createdat text default (timezone('utc', now())::text),
  readat text default '',
  unique(memberid, scheduleid, channel)
);

create index if not exists idx_notifications_member
  on public.notifications(memberid, status, createdat);

create table if not exists public.learning_progress (
  memberid text not null,
  courseid text not null,
  activeindex integer default 0,
  completedcount integer default 0,
  totalmodules integer default 0,
  moduletitle text default '',
  updatedat text default (timezone('utc', now())::text),
  primary key (memberid, courseid)
);

create index if not exists idx_learning_progress_member
  on public.learning_progress(memberid, updatedat);

create table if not exists public.payment_records (
  id text primary key,
  memberid text not null,
  provider text default 'stripe',
  status text default 'pending',
  paymentmethod text default '',
  productname text default 'AiX Member',
  amount integer default 0,
  amountsubtotal integer default 0,
  amountdiscount integer default 0,
  amounttax integer default 0,
  currency text default 'thb',
  stripecustomerid text default '',
  stripesessionid text default '',
  stripepaymentintentid text default '',
  stripechargeid text default '',
  receipturl text default '',
  invoiceurl text default '',
  promotioncode text default '',
  couponname text default '',
  metadata text default '{}',
  paidat text default '',
  createdat text default (timezone('utc', now())::text),
  updatedat text default (timezone('utc', now())::text)
);

create index if not exists idx_payment_records_member
  on public.payment_records(memberid, createdat);

create unique index if not exists idx_payment_records_session
  on public.payment_records(stripesessionid)
  where stripesessionid <> '';

create unique index if not exists idx_payment_records_intent
  on public.payment_records(stripepaymentintentid)
  where stripepaymentintentid <> '';

create unique index if not exists idx_payment_records_charge
  on public.payment_records(stripechargeid)
  where stripechargeid <> '';

alter table public.courses enable row level security;
alter table public.leads enable row level security;
alter table public.users enable row level security;
alter table public.members enable row level security;
alter table public.packages enable row level security;
alter table public.sms_verifications enable row level security;
alter table public.course_replays enable row level security;
alter table public.member_resources enable row level security;
alter table public.class_schedules enable row level security;
alter table public.notifications enable row level security;
alter table public.learning_progress enable row level security;
alter table public.payment_records enable row level security;

revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
